### ISSUE TITLE
couldn't find "libRPPG.so"

### ISSUE THREAD

**Issue by egzon123** [prouast/heartbeat-android#2]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.prouast.heartbeat-1/base.apk"],nativeLibraryDirectories=[/data/app/com.prouast.heartbeat-1/lib/arm64, /data/app/com.prouast.heartbeat-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libRPPG.so"

**Comment by xwf12345678** [comment]
I also meet this problems. Do you sovle it?
